### ISSUE TITLE
grafana hook update-status failed

### ISSUE THREAD

**Issue by tkalpakidis** [juju-solutions/bundle-canonical-kubernetes#597]
trying to deploy canonical kubernetes on localhost lxd firing conjure-up
I get hook failed: "update-status" for grafana unit. All other units of the bundle finish succesfully

investigating the logs on grafana unit i get the following:

2018-06-22 11:35:16 DEBUG update-status UPDATE DATA_SOURCE SET basic_auth_user = ?, basic_auth_password = ?, basic_auth = 0 ('', '')
2018-06-22 11:35:16 DEBUG update-status Traceback (most recent call last):
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/charm/hooks/update-status", line 19, in <module>
2018-06-22 11:35:16 DEBUG update-status     main()
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 72, in main
2018-06-22 11:35:16 DEBUG update-status     bus.dispatch(restricted=restricted_mode)
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 375, in dispatch
2018-06-22 11:35:16 DEBUG update-status     _invoke(other_handlers)
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 351, in _invoke
2018-06-22 11:35:16 DEBUG update-status     handler.invoke()
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 173, in invoke
2018-06-22 11:35:16 DEBUG update-status     self._action(*args)
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/charm/reactive/grafana.py", line 382, in configure_sources
2018-06-22 11:35:16 DEBUG update-status     generate_prometheus_dashboards(gf_adminpasswd, ds)
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/charm/reactive/grafana.py", line 561, in generate_prometheus_dashboards
2018-06-22 11:35:16 DEBUG update-status     hookenv.log(errmsg.format(DASH_TMPL, r.text))
2018-06-22 11:35:16 DEBUG update-status   File "/var/lib/juju/agents/unit-grafana-0/.venv/lib/python3.5/site-packages/charmhelpers/core/hookenv.py", line 105, in log
2018-06-22 11:35:16 DEBUG update-status     subprocess.call(command)
2018-06-22 11:35:16 DEBUG update-status   File "/usr/lib/python3.5/subprocess.py", line 557, in call
2018-06-22 11:35:16 DEBUG update-status     with Popen(*popenargs, **kwargs) as p:
2018-06-22 11:35:16 DEBUG update-status   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
2018-06-22 11:35:16 DEBUG update-status     restore_signals, start_new_session)
2018-06-22 11:35:16 DEBUG update-status   File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
2018-06-22 11:35:16 DEBUG update-status     restore_signals, start_new_session, preexec_fn)
2018-06-22 11:35:16 DEBUG update-status **UnicodeEncodeError: 'ascii' codec can't encode characters in position 3957-3960: ordinal not in range(128)**
2018-06-22 11:35:16 ERROR juju.worker.uniter.operation runhook.go:113 hook "update-status" failed: exit status 1
2018-06-22 11:35:16 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "update-status" hook

**Comment by kwmonroe** [comment]
@tkalpakidis please share the output of `juju status` in your failed deployment.  The error is coming from the grafana charm here:

https://git.launchpad.net/grafana-charm/tree/reactive/grafana.py#n560

It's trying to tell us why the dashboard post didn't come back with a 200.  There's something in that request response that isn't being decoded, but it would be useful to see your `juju status` output to know which dashboard is being loaded (i'm guessing it's the telegraf db).

**Comment by tkalpakidis** [comment]
here is `juju status`

Unit                      Workload  Agent  Machine  Public address  Ports                                    Message
apache2/0*                unknown   idle   0        10.121.102.6
easyrsa/0*                active    idle   1        10.121.102.124                                           Certificate Authority connected.
elasticsearch/0*          active    idle   2        10.121.102.145  9200/tcp                                 Ready
etcd/0                    active    idle   3        10.121.102.115  2379/tcp                                 Healthy with 3 known peers
etcd/1                    active    idle   4        10.121.102.54   2379/tcp                                 Healthy with 3 known peers
etcd/2*                   active    idle   5        10.121.102.186  2379/tcp                                 Healthy with 3 known peers
grafana/0*                error     idle   6        10.121.102.126  3000/tcp                                 hook failed: "update-status"
graylog/0*                active    idle   7        10.121.102.253                                           Ready with: filebeat, elasticsearch, mongodb
kubeapi-load-balancer/0*  active    idle   8        10.121.102.60   443/tcp                                  Loadbalancer ready.
kubernetes-master/0*      active    idle   9        10.121.102.13   6443/tcp                                 Kubernetes master running.
  filebeat/0              active    idle            10.121.102.13                                            Filebeat ready.
  flannel/0               active    idle            10.121.102.13                                            Flannel subnet 10.1.63.1/24
  telegraf/0              active    idle            10.121.102.13   9103/tcp                                 Monitoring kubernetes-master/0
kubernetes-worker/0*      active    idle   10       10.121.102.50   80/tcp,443/tcp                           Kubernetes worker running.
  filebeat/1              active    idle            10.121.102.50                                            Filebeat ready.
  flannel/1               active    idle            10.121.102.50                                            Flannel subnet 10.1.91.1/24
  telegraf/1              active    idle            10.121.102.50   9103/tcp                                 Monitoring kubernetes-worker/0
kubernetes-worker/1       active    idle   11       10.121.102.125  80/tcp,443/tcp                           Kubernetes worker running.
  filebeat/2              active    idle            10.121.102.125                                           Filebeat ready.
  flannel/2               active    idle            10.121.102.125                                           Flannel subnet 10.1.40.1/24
  telegraf/2              active    idle            10.121.102.125  9103/tcp                                 Monitoring kubernetes-worker/1
kubernetes-worker/2       active    idle   12       10.121.102.83   80/tcp,443/tcp                           Kubernetes worker running.
  filebeat/3*             active    idle            10.121.102.83                                            Filebeat ready.
  flannel/3*              active    idle            10.121.102.83                                            Flannel subnet 10.1.92.1/24
  telegraf/3*             active    idle            10.121.102.83   9103/tcp                                 Monitoring kubernetes-worker/2
mongodb/0*                unknown   idle   13       10.121.102.5    27017/tcp,27019/tcp,27021/tcp,28017/tcp
prometheus/0*             active    idle   14       10.121.102.251  9090/tcp,12321/tcp                       Ready

Machine  State    DNS             Inst id         Series  AZ  Message
0        started  10.121.102.6    juju-f64cfb-0   xenial      Running
1        started  10.121.102.124  juju-f64cfb-1   xenial      Running
2        started  10.121.102.145  juju-f64cfb-2   xenial      Running
3        started  10.121.102.115  juju-f64cfb-3   xenial      Running
4        started  10.121.102.54   juju-f64cfb-4   xenial      Running
5        started  10.121.102.186  juju-f64cfb-5   xenial      Running
6        started  10.121.102.126  juju-f64cfb-6   xenial      Running
7        started  10.121.102.253  juju-f64cfb-7   xenial      Running
8        started  10.121.102.60   juju-f64cfb-8   xenial      Running
9        started  10.121.102.13   juju-f64cfb-9   xenial      Running
10       started  10.121.102.50   juju-f64cfb-10  xenial      Running
11       started  10.121.102.125  juju-f64cfb-11  xenial      Running
12       started  10.121.102.83   juju-f64cfb-12  xenial      Running
13       started  10.121.102.5    juju-f64cfb-13  xenial      Running
14       started  10.121.102.251  juju-f64cfb-14  xenial      Running

**Comment by kwmonroe** [comment]
@tkalpakidis i'm having trouble reproducing the failed dashboard import.  Could you provide the following if you still have a reproducible env?

- conjure-up --version
- juju version
- locale
- juju status telegraf prometheus grafana --relations

For reference, here's what my attempt looks like when i conjure-up cdk + prometheus with a lxd controller:
```bash
ubuntu@ip-172-31-3-116:~⟫ conjure-up --version
conjure-up 2.5.7

ubuntu@ip-172-31-3-116:~⟫ juju version
2.3.8-xenial-amd64

ubuntu@ip-172-31-3-116:~⟫ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

ubuntu@ip-172-31-3-116:~⟫ juju status telegraf prometheus grafana --relations
Model                         Controller  Cloud/Region         Version  SLA
conjure-canonical-kubern-886  lxd-test    localhost/localhost  2.3.8    unsupported

App                Version  Status  Scale  Charm              Store       Rev  OS      Notes
grafana                     active      1  grafana            jujucharms   11  ubuntu  exposed
kubernetes-master  1.10.4   active      1  kubernetes-master  jujucharms  113  ubuntu
kubernetes-worker  1.10.4   active      1  kubernetes-worker  jujucharms  128  ubuntu  exposed
prometheus                  active      1  prometheus         jujucharms    6  ubuntu
telegraf                    active      2  telegraf           jujucharms   13  ubuntu

Unit                  Workload  Agent  Machine  Public address  Ports               Message
grafana/0*            active    idle   2        10.232.92.138   3000/tcp            Started grafana-server
kubernetes-master/0*  active    idle   4        10.232.92.30    6443/tcp            Kubernetes master running.
  flannel/0*          active    idle            10.232.92.30                        Flannel subnet 10.1.14.1/24
  telegraf/0*         active    idle            10.232.92.30    9103/tcp            Monitoring kubernetes-master/0
kubernetes-worker/0*  active    idle   5        10.232.92.230   80/tcp,443/tcp      Kubernetes worker running.
  flannel/1           active    idle            10.232.92.230                       Flannel subnet 10.1.82.1/24
  telegraf/1          active    idle            10.232.92.230   9103/tcp            Monitoring kubernetes-worker/0
prometheus/0*         active    idle   6        10.232.92.71    9090/tcp,12321/tcp  Ready

Entity  Meter status  Message
model   amber         user verification pending

Machine  State    DNS            Inst id        Series  AZ  Message
2        started  10.232.92.138  juju-56c1d8-2  xenial      Running
4        started  10.232.92.30   juju-56c1d8-4  xenial      Running
5        started  10.232.92.230  juju-56c1d8-5  xenial      Running
6        started  10.232.92.71   juju-56c1d8-6  xenial      Running

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:juju-info          telegraf:juju-info                   juju-info         subordinate
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-worker:juju-info          telegraf:juju-info                   juju-info         subordinate
prometheus:grafana-source            grafana:grafana-source               grafana-source    regular
telegraf:prometheus-client           prometheus:target                    http              regular
```

**Comment by tkalpakidis** [comment]
hello here is my output

```
tkalpakid@tplkubahr01:~$ conjure-up --version
conjure-up 2.5.7
tkalpakid@tplkubahr01:~$ juju version
2.3.8-xenial-amd64
tkalpakid@tplkubahr01:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
tkalpakid@tplkubahr01:~$ juju status telegraf prometheus grafana --relations
Model                         Controller                Cloud/Region         Version  SLA
conjure-canonical-kubern-dd0  conjure-up-localhost-528  localhost/localhost  2.3.8    unsupported

App                Version  Status  Scale  Charm              Store       Rev  OS      Notes
flannel            0.9.1    active      0  flannel            jujucharms   59  ubuntu
grafana                     error       1  grafana            jujucharms   12  ubuntu  exposed
kubernetes-master  1.10.5   active      1  kubernetes-master  jujucharms  113  ubuntu
kubernetes-worker  1.10.5   active      3  kubernetes-worker  jujucharms  128  ubuntu  exposed
prometheus                  active      1  prometheus         jujucharms    6  ubuntu
telegraf                    active      4  telegraf           jujucharms   13  ubuntu

Unit                  Workload  Agent  Machine  Public address  Ports               Message
grafana/0*            error     idle   6        10.121.102.126  3000/tcp            hook failed: "update-status"
kubernetes-master/0*  active    idle   9        10.121.102.13   6443/tcp            Kubernetes master running.
  filebeat/0          active    idle            10.121.102.13                       Filebeat ready.
  flannel/0           active    idle            10.121.102.13                       Flannel subnet 10.1.63.1/24
  telegraf/0          active    idle            10.121.102.13   9103/tcp            Monitoring kubernetes-master/0
kubernetes-worker/0*  active    idle   10       10.121.102.50   80/tcp,443/tcp      Kubernetes worker running.
  filebeat/1          active    idle            10.121.102.50                       Filebeat ready.
  flannel/1           active    idle            10.121.102.50                       Flannel subnet 10.1.91.1/24
  telegraf/1          active    idle            10.121.102.50   9103/tcp            Monitoring kubernetes-worker/0
kubernetes-worker/1   active    idle   11       10.121.102.125  80/tcp,443/tcp      Kubernetes worker running.
  filebeat/2          active    idle            10.121.102.125                      Filebeat ready.
  flannel/2           active    idle            10.121.102.125                      Flannel subnet 10.1.40.1/24
  telegraf/2          active    idle            10.121.102.125  9103/tcp            Monitoring kubernetes-worker/1
kubernetes-worker/2   active    idle   12       10.121.102.83   80/tcp,443/tcp      Kubernetes worker running.
  filebeat/3*         active    idle            10.121.102.83                       Filebeat ready.
  flannel/3*          active    idle            10.121.102.83                       Flannel subnet 10.1.92.1/24
  telegraf/3*         active    idle            10.121.102.83   9103/tcp            Monitoring kubernetes-worker/2
prometheus/0*         active    idle   14       10.121.102.251  9090/tcp,12321/tcp  Ready

Entity  Meter status  Message
model   amber         user verification pending

Machine  State    DNS             Inst id         Series  AZ  Message
6        started  10.121.102.126  juju-f64cfb-6   xenial      Running
9        started  10.121.102.13   juju-f64cfb-9   xenial      Running
10       started  10.121.102.50   juju-f64cfb-10  xenial      Running
11       started  10.121.102.125  juju-f64cfb-11  xenial      Running
12       started  10.121.102.83   juju-f64cfb-12  xenial      Running
14       started  10.121.102.251  juju-f64cfb-14  xenial      Running

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:juju-info          filebeat:beats-host                  juju-info         subordinate
kubernetes-master:juju-info          telegraf:juju-info                   juju-info         subordinate
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-worker:juju-info          filebeat:beats-host                  juju-info         subordinate
kubernetes-worker:juju-info          telegraf:juju-info                   juju-info         subordinate
prometheus:grafana-source            grafana:grafana-source               grafana-source    regular
telegraf:prometheus-client           prometheus:target                    http              regular

**Comment by tkalpakidis** [comment]
please note i'm deploying behind a corporate proxy, i had a few issues with that but i managed to get at this point at least. In fact the cluster works fine... i just can't understand why juju stuck there...

**Comment by kwmonroe** [comment]
@tkalpakidis just a heads' up that grafana and telgraf have had some recent changes with loading dashboards.. Perhaps an upgrade to the latest charm revs will fix this.

I did try setting up a restricted env (where things go through an http(s) proxy), but was unable to repro this.  My relevant updated charms from `juju status` are:
```
grafana               active      1  grafana      jujucharms   17  ubuntu  exposed
prometheus            active      1  prometheus   jujucharms    7  ubuntu
telegraf              active      1  telegraf     jujucharms   16  ubuntu
```

If this is still an issue for you, would you please try to use the more recent charm revisions for the above charms?  If that doesn't work, can you describe your proxy environment a bit more?  Seeing things like `juju model-config` to show any proxy config would be useful.  Thanks for sticking with me as I try to track this down!

**Comment by kwmonroe** [comment]
This is pretty stale now, and since I'm unable to repro in a proxied env with the latest charms, I think this is fixed.  Closing out.

**Comment by tkalpakidis** [comment]
Thanks for your time checking my issue, i eventually destroyed that environment and moved on. But i will  revisit soon so if i still have the issue i'll let you know.
