### ISSUE TITLE
RBAC enabled results in error: unable to upgrade connection: Forbidden (user=client, verb=create, resource=nodes, subresource=proxy) on kubectl exec

### ISSUE THREAD

**Issue by kowalczykb** [juju-solutions/bundle-canonical-kubernetes#696]
Deploying CDK 1.10 with RBAC (i am also testing 1.11 and 1.12 and will report back later/tomorrow)  results in:
error: unable to upgrade connection: Forbidden (user=client, verb=create, resource=nodes, subresource=proxy)

when running `kubectl exec`

**`$ kubectl exec -it busybox-5858cc4697-pgqw5 -- /bin/sh`**
` `
`error: unable to upgrade connection: Forbidden (user=client, verb=create, resource=nodes, subresource=proxy)`

The same bundle deployed with RBAC disabled in yaml works fine and doesn't show this behaviour

[juju-status-output.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2611733/juju-status-output.txt)
[kubectl-get-all-all-namespaces.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2611734/kubectl-get-all-all-namespaces.txt)

[cdk-bundle.yaml.txt](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2611735/cdk-bundle.yaml.txt)
[results-2018-11-23-20-54-13.tar.gz](https://github.com/juju-solutions/bundle-canonical-kubernetes/files/2611736/results-2018-11-23-20-54-13.tar.gz)

**Comment by Cynerva** [comment]
This is closely related to https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/642, which was fixed by https://github.com/juju-solutions/kubernetes/pull/188. That fix has not made it to stable yet.

However, the error reported in this bug shows `verb=create`, a permission which was not included in that fix. So we probably need to expand those permissions before we can close this.

**Comment by ktsakalozos** [comment]
Thank you @Cynerva 

@kowalczykb the workaround here https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/642#issuecomment-418327745 seems to be working for your case

**Comment by tvansteenburgh** [comment]
This was mostly fixed by the changes made for https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/642, but it looks like the charm only applies the fix on fresh deployments or on config.changed.authorizaton-mode, and *not* on upgrade-charm. We need to finish that part.

**Comment by nicklasfrahm** [comment]
@tvansteenburgh I am still experiencing this problem in a new CDK cluster with k8s `1.13`. I was using `kubectl port-forward`, while getting the same error: `error: error upgrading connection: unable to upgrade connection: Forbidden (user=client, verb=create, resource=nodes, subresource=proxy)`.

As I can see, there is a fix applied to new CDK clusters via the following resources:
- clusterrole: `proxy-clusterrole-kubernetes-master`
- clusterrolebinding: `proxy-role-binding-kubernetes-master`.

Applying a small configuration change to the clusterrole `proxy-clusterrole-kubernetes-master`, fixed it for me:

```diff
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-clusterrole-kubernetes-master
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
+     - create
```

I think this could potentially be a better fix that the one mentioned in [this comment of #642](https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/642#issuecomment-418327745).

**Comment by joedborg** [comment]
https://github.com/juju-solutions/kubernetes/pull/206

**Comment by joedborg** [comment]
Available from kubernetes-master-578
